2024-12-28 11:31:12,189 - INFO - Application starting.
2024-12-28 11:31:12,190 - INFO - Starting stream listener for camera: Test Camera
2024-12-28 11:31:12,190 - INFO - Starting message queue processor.
2024-12-28 11:31:12,193 - INFO - Starting periodic tasks thread.
2024-12-28 11:31:12,194 - INFO - Alert counts logged.
2024-12-28 11:31:12,194 - INFO - Alert counts reset for all cameras.
2024-12-28 11:32:01,724 - INFO - Message sent to Telegram.
2024-12-28 11:34:44,422 - INFO - Message sent to Telegram.
2024-12-28 11:34:53,207 - INFO - Message sent to Telegram.
2024-12-28 11:35:03,035 - INFO - KeyboardInterrupt detected. Shutting down.
2024-12-28 11:35:03,037 - INFO - Shutdown complete.
2024-12-30 13:50:02,960 - INFO - Application starting.
2024-12-30 13:50:02,964 - INFO - Loaded 0 messages from persistent queue.
2024-12-30 13:50:02,966 - INFO - Starting stream listener for camera: test camera
2024-12-30 13:50:02,970 - INFO - Starting message queue processor.
2024-12-30 13:50:02,970 - INFO - Starting periodic tasks thread.
2024-12-30 13:50:02,971 - INFO - Alert counts logged.
2024-12-30 13:50:02,972 - INFO - Alert counts reset for all cameras.
2024-12-30 13:50:23,998 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B03A0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:50:55,075 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B10F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:51:26,144 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B1990>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:51:57,206 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B2230>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:52:28,268 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B1A50>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:52:59,349 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D4C67B11B0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 13:53:22,742 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D4C67B0370>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2024-12-30 13:54:03,804 - INFO - Application starting.
2024-12-30 13:54:03,805 - INFO - Loaded 0 messages from persistent queue.
2024-12-30 13:54:03,807 - INFO - Starting stream listener for camera: test camera
2024-12-30 13:54:03,809 - INFO - Starting message queue processor.
2024-12-30 13:54:03,811 - INFO - Starting periodic tasks thread.
2024-12-30 13:54:03,812 - INFO - Alert counts logged.
2024-12-30 13:54:03,813 - INFO - Alert counts reset for all cameras.
2024-12-30 13:55:05,613 - ERROR - Failed to send Telegram message: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7802711134:AAELuoLMl9mXncmOuAdYjU_Kw4eHKCdYkT8/sendMessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002F3A52B21A0>, 'Connection to api.telegram.org timed out. (connect timeout=10)'))
2024-12-30 13:55:35,714 - ERROR - Failed to send Telegram message: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7802711134:AAELuoLMl9mXncmOuAdYjU_Kw4eHKCdYkT8/sendMessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002F3A52B2680>, 'Connection to api.telegram.org timed out. (connect timeout=10)'))
2024-12-30 13:55:44,300 - INFO - KeyboardInterrupt detected. Shutting down.
2024-12-30 13:55:44,305 - INFO - Shutdown complete.
2024-12-30 14:10:02,937 - INFO - Application starting.
2024-12-30 14:10:02,940 - INFO - Loaded 0 messages from persistent queue.
2024-12-30 14:10:02,941 - INFO - Starting stream listener for camera: test camera
2024-12-30 14:10:02,942 - INFO - Starting message queue processor.
2024-12-30 14:10:02,943 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E80F9F03A0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
2024-12-30 14:10:02,943 - INFO - Starting periodic tasks thread.
2024-12-30 14:10:02,944 - INFO - Alert counts logged.
2024-12-30 14:10:02,944 - INFO - Alert counts reset for all cameras.
2024-12-30 14:10:12,967 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E80F9F1120>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
2024-12-30 14:10:46,781 - ERROR - Stream error for test camera: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-12-30 14:10:46,781 - ERROR - Failed to send Telegram message: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7802711134:AAELuoLMl9mXncmOuAdYjU_Kw4eHKCdYkT8/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80F9F21A0>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
2024-12-30 14:11:20,196 - ERROR - Failed to send Telegram message: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7802711134:AAELuoLMl9mXncmOuAdYjU_Kw4eHKCdYkT8/sendMessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E80F9F30A0>, 'Connection to api.telegram.org timed out. (connect timeout=10)'))
2024-12-30 14:11:50,213 - ERROR - Failed to send Telegram message: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7802711134:AAELuoLMl9mXncmOuAdYjU_Kw4eHKCdYkT8/sendMessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E80F9F3BE0>, 'Connection to api.telegram.org timed out. (connect timeout=10)'))
2024-12-30 14:11:56,845 - ERROR - Stream error for test camera: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-12-30 14:12:01,258 - INFO - Message sent to Telegram.
2024-12-30 14:12:02,330 - INFO - Message sent to Telegram.
2024-12-30 14:12:03,100 - INFO - Message sent to Telegram.
2024-12-30 14:12:27,905 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1AB0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:12:58,961 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2E90>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:13:30,020 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1F90>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:14:01,089 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1720>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:14:32,144 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F99BAF0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:15:03,198 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F0C40>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:15:34,840 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F28F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:16:05,902 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1900>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:16:36,960 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3CA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:17:08,012 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA407C0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:17:39,079 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2E00>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:18:10,127 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2B00>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:18:41,164 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1060>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:19:12,216 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3FA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:19:43,273 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA40520>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:20:14,338 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1AE0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:20:45,424 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F28F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:21:16,492 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1900>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:21:47,535 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3CA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:22:18,595 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA40730>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:22:49,648 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3CA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:23:20,710 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1900>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:23:51,764 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F28F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:24:22,820 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F0DF0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:24:53,872 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA407F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:25:24,911 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F0FA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:25:55,972 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1450>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:26:27,035 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2D10>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:26:58,095 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1810>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:27:29,172 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2320>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:28:00,215 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3AF0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:28:31,270 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1AB0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:29:02,326 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F18A0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:29:33,387 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1240>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:30:04,462 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3FA0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:30:35,514 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F0DC0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:31:06,591 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2980>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:31:37,662 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F16F0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:32:08,746 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3BB0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:32:39,795 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3430>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:33:10,857 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA41060>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:33:41,895 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3BE0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:34:12,962 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3010>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:34:44,018 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F0760>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:35:15,098 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F11E0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:35:46,164 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA40C40>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:36:17,213 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F1A80>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:36:48,269 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2020>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:37:19,327 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F2F50>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:37:50,356 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80F9F3A30>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:38:21,422 - ERROR - Stream error for test camera: HTTPConnectionPool(host='192.168.1.245', port=80): Max retries exceeded with url: /cgi-bin/eventManager.cgi?action=attach&codes=%5BAlarmLocal%2CVideoMotion%5D&heartbeat=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E80FA40FD0>, 'Connection to 192.168.1.245 timed out. (connect timeout=30)'))
2024-12-30 14:38:34,866 - INFO - KeyboardInterrupt detected. Shutting down.
2024-12-30 14:38:34,872 - INFO - Shutdown complete.
